name: PlanetFxIceHockey
version: 1.0
author: Sebastian Mikolai

main: de.SebastianMikolai.PlanetFx.PlanetFxIceHockey.HG

commands:
  hockey:
    description: PlanetFxIceHockey Commands
    usage: /hockey